# Generated by Django 4.1.1 on 2023-02-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course_subject_allocation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='lmsmainapp.course'),
        ),
    ]
