# Generated by Django 4.1.1 on 2023-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0002_examresult_no_of_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_master',
            name='correct_mark',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exam_master',
            name='incorrect_mark',
            field=models.FloatField(default=0),
        ),
    ]
