# Generated by Django 4.1.1 on 2023-03-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0003_exam_master_correct_mark_exam_master_incorrect_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='testimonial')),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
    ]
