# Generated by Django 4.1.1 on 2023-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0004_enquiry_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='datetime',
            new_name='date',
        ),
    ]
