# Generated by Django 4.1.1 on 2023-03-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0005_rename_datetime_testimonial_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='date',
            new_name='datetime',
        ),
    ]
