# Generated by Django 4.1.1 on 2023-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0006_rename_date_testimonial_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='token',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
