# Generated by Django 4.1.1 on 2023-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0007_login_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='token',
        ),
        migrations.AddField(
            model_name='login',
            name='deviceId',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
