# Generated by Django 4.1.1 on 2023-03-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsmainapp', '0008_remove_login_token_login_deviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='token',
        ),
    ]
